on:
  push:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy openapi.yml
        run: cp ./src/main/resources/static/openapi.yml ./doc/swagger-ui-3.51.1/dist/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/swagger-ui-3.51.1/dist
