on:
  push:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy openapi.yml
        run: cp ./src/main/resources/static/openapi.yml ./doc/swagger-ui-3.51.1/dist/
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar
