on:
  workflow_run:
    workflows: [".github/workflows/build.yml"]
    types: ["completed"]
    branches: [main, develop, "release/**"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy openapi.yml
        run: cp ./src/main/resources/static/openapi.yml ./doc/swagger-ui-3.51.1/dist/
      - name: Publish swagger to github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/swagger-ui-3.51.1/dist
          force_orphan: true
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io/opgg-hackthon
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Push container to registry
        run: ./gradlew jib -Djib.to.tags=${{ env.BRANCH_NAME }}
